### ISSUE TITLE
List of custom file extensions

### ISSUE THREAD

**Issue by n1kk** [kddnewton/prettier-plugin-ini#516]
Hi! Would it be possible to add an ability to specify a list of custom extensions that have `ini` format?

I wanted this plugin to format my `.env` files, but sadly it doesn't consider them supported. `.env` and `.env.*` are pretty standard in JS development for defining custom environment variables via dotenv. I looked into the `linguist` repo and sadly they identify them as Shell scripts for now, there was a commit to move them to their own language category but it was [reverted](https://github.com/github/linguist/commit/712a1ee719675c98be4edd5337c71862c50c4e30), wrong branch, so maybe it'll come in future, but even then they only list `.env` and `.env.example` in the list and don't mark it as `ini`. 

A lot of JS/TS projects and boilerplates use convention of `.env`, `.env.local` and `.env.MODE`, `.env.MODE.local`, ie: `.env.development.local`.

So since it can be quite unique to a project maybe adding a way to specify a list of custom extensions could be useful?

**Comment by kddnewton** [comment]
Yeah you should be able to do this with prettier itself, using configuration overrides, as in:

https://prettier.io/docs/en/configuration.html#setting-the-parserdocsenoptionshtmlparser-option

**Comment by n1kk** [comment]
Oh, nice, thanks!

Will leave this for the record since it's not super obvious whats the name of the parser is :)

`prettier.config.json`
```json

{
  "overrides": [
    {
      "files": [".env", ".env.*"],
      "options": {
        "parser": "ini",
      }
    }
  ]
}
```

But I've found that formatting with this plugin is removing empty lines from my `.env` files, so I switched to a `prettier-plugin-sh` plugin.
