### ISSUE TITLE
Not working with prettier@3.0.3

### ISSUE THREAD

**Issue by danil51608** [kddnewton/prettier-plugin-ini#575]
Getting an error and warnings trying to run with the plugin on prettier@3.0.3

```shell

[warn] Ignored unknown option { iniSpaceAroundEquals: true }.
.editorconfig
[error] Couldn't resolve parser "ini".
```

My .prettierrc file

```ini
iniSpaceAroundEquals: true
overrides:
  - files: ".prettierrc"
    options:
        parser: yaml
  - files: ".editorconfig"
     options:
         parser: ini
```

The plugin work well with prettier v2.7.1
Is prettier v3.0.3 supported by the plugin?

**Comment by kddnewton** [comment]
In prettier 3 you have to specify the plugins, it doesn't automatically pick them up anymore.
